/**
 * 
 * @authors Your Name (you@example.org)
 * @date    2017-02-15 16:06:16
 * @version $Id$
 */
var nwdHead = [];
nwdHead = [
	'<div class="header">',
	'	<div class="nwd_top">',
	'		<div class="nwd_main pad_t10 clearfix">',
	'			<span class="fl fs_16 fc_9"><i class="icon icon_tel">&nbsp;</i>客服热线<em class="Numfont mar_l10">&nbsp;400-791-0888</em></span>',
	'			<span class="fr fc_9 mar_l10">市场有风险，投资需谨慎</span>',
	'			<span class="fr"><a href="http://weibo.com/niwodai" target="_blank" class="link_weixin"><i class="icon icon_weixin">&nbsp;</i></a></span>',
	'			<span class="fr mar_r10"><a href="javascript:()" class="link_weibo mar_r10" target="_blank"><i class="icon icon_weibo">&nbsp;</i>微信客服<img src="https://static.niwodai.com/Public/Static/201603/css/font/topbg_b14925.png" class="weixinImg"></a></span>',
	'			<span class="fr">',
	'				<a href="http://www.niwodai.com/index.do?method=ac&amp;artId=3800000395842909" class="link_mobile mar_r20" target="_blank"><i class="icon icon_moible">&nbsp;</i>手机客户端<img src="https://static.niwodai.com/Public/Static/201603/css/font/topbg_b14926.png" usemap="#Map" class="mobileImg">',
	'					<map name="Map">',
	'						<area shape="rect" coords="154,40,256,153" href="http://www.niwodai.com/event.mhtml?&amp;artId=3800000395842909" target="_blank">',
	'						<area shape="rect" coords="424,41,517,150" href="http://www.niwodai.com/event.mhtml?&amp;artId=3800000794998139" target="_blank">',
	'		            </map>',
	'				</a>',
	'			</span>',
	'			<input type="hidden" value="234e9ccf-e9c8-4676-a9f9-f01b9948b361" id="stok">',
	'		  	<input type="hidden" value="3820150011007624" id="log_userid">',
	'	      	<input type="hidden" value="nwdvy97ju" id="log_username">',
	'		  	<span class="fr fc_9" id="login_bt">您好，<a href="https://member.niwodai.com/login.html" class="mar_l10 toplogin" title="登录">请登录</a><a href="http://www.niwodai.com/register.html" class="mar_r10 mar_l10 toplogin" title="注册">免费注册</a></span>',
	'		</div>',
	'	</div>',
	'	<div class="nwd_menu">',
	'		<div class="nwd_main">',
	'			<h1 class="fl logo mar_t20"><a title="给梦想可能" href="http://www.niwodai.com"><img height="52" alt="你我贷" src="https://static.niwodai.com/Public/Static/201603/images/logo.png"></a></h1>',
	'			<div class="fl slogan" id="headLogo">',
	'				<a href="http://www.niwodai.com" class="pad_t20"><img src="https://static.niwodai.com/Public/Static/201603/images/slogan.png" align="给梦想可能"></a>',
	'			</div>',
	'			<div class="fr nwd_navCon  mar_t20">',
	'				<ul class="nav clearfix">',
	'					<li>',
	'						<a title="首页" href="http://www.niwodai.com" rel="nofollow" class="nav_link">首页</a>',
	'					</li>',
	'					<li class="two cur_two">',
	'						<div class="investCon">',
	'							<div class="invest_name">',
	'								<a href="https://member.niwodai.com/xiangmu" class="fs_16">我要投资</a>',
	'								<em class="icon_base icon_base_navedown mar_l10"></em>',
	'							</div>',
	'							<div class="invest_list" style="overflow: hidden; height: 120px; display: none; margin-top: 0px; margin-bottom: 0px; padding-top: 5px; padding-bottom: 0px;">',
	'								<a href="https://member.niwodai.com/financial/financialDetail.do" class="investName_link">嘉财有道</a>',
	'								<a href="https://member.niwodai.com/baiduFina/newPeople.do" class="investName_link">新手专区</a>',
	'								<a href="https://member.niwodai.com/xiangmu" class="investName_link">新标专区</a>',
	'								<a href="https://member.niwodai.com/zhuanrang/" class="investName_link">转让专区</a>',
	'							</div>',
	'						</div>',
	'					</li>',
	'					<li class="rela">',
	'                      <div class="investCon">',
	'                            <div class="invest_name">',
	'                                <a title="我要借款" href="http://www.niwodai.com/daikuan/" class="fs_16">我要借款</a>',
	'                                <em class="icon_base  icon_base_navedown  mar_l10"></em>',
	'                            </div>',
	'                            <div class="invest_list" style="overflow: hidden; height: 60px; display: none; margin-top: 0px; margin-bottom: 0px; padding-top: 5px; padding-bottom: 0px;">',
	'                                <a href="http://www.niwodai.com/daikuan/jiekuan.html" class="investName_link">借款产品</a>',
	'                                <a href="http://www.niwodai.com/help/jiekshenqing.html" class="investName_link">借款攻略</a>',
	'                            </div>',
	'                       </div>',
	'                    </li>',
	'					<li class="rela">',
	'						<a title="新手导航" href="http://www.niwodai.com/activity.mhtml?artId=3800001227739922&amp;f&amp;h" target="_blank" class="nav_link">新手导航 </a>',
	'					</li>',
	'					<li>',
	'						<a title="社区" href="http://club.niwodai.com" target="_blank" class="nav_link">社区 </a>',
	'					</li>',
	'					<li class="two"> ',
	'						<a href="http://static2.niwodai.com/Public/Static/nwd/website/pc/disclosure/index.html" class="nav_link">信息披露</a> ',
	'					</li>',
	'					<li class="myuserCon" style="margin-right:0;">',
	'						<div class="LedgerCon wid_w180">',
	'							<a class="navphoto fs_16 fl mar_l10" href="https://member.niwodai.com/member/Investors.html" title="我的账户"><i class="mar_r5 relative">',
	'							<img id="small-tx" src="https://static.niwodai.com/Public/Static/201603/manage/img/smalltx.png">',
	'							<img id="smallImg" alt="头像" src="https://static.niwodai.com/Public/Static/201603/manage/images/touxiang.jpg" class="smallmytxPic">',
	'							</i></a>',
	'							<div class="Ledger_name pad_t5">',
	'								<a title="我的账户" class="fs_16">我的账户</a>',
	'								<em class="icon_base icon_base_navedown mar_l5"></em>',
	'							</div>',
	'							<div class="Ledger_list clearfix pad_l10 pad_r10" style="overflow: hidden; height: 160px; display: none; margin-top: 25px; margin-bottom: 0px; padding-top: 15px; padding-bottom: 0px;">',
	'								<a href="https://member.niwodai.com/member/memberMsg.do" class="listName_link"><span class="fl">消息中心</span></a>',
	'								<a href="https://member.niwodai.com/member/fundsLog.html" class="listName_link">资金记录</a>',
	'									<a href="https://member.niwodai.com/member/findFinancial2Page.do" class="listName_link">嘉财有道</a>',
	'								<a href="https://member.niwodai.com/member/myAcceptList.html" class="listName_link">我的债权</a>',
	'							</div>',
	'						</div>',
	'					</li>',
	'				</ul>',
	'			</div>',
	'		</div>',
	'	</div>',
	'</div>'
].join("");
$("#nwdHead").html(nwdHead);